[package]
name = "gossip"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
libp2p = {version = "0.56.0", features = ["mdns", "noise", "tcp", "yamux", "tokio", "ping"]}
rand = "0.9.2"
tokio = {version = "1.48.0", features = ["full"]}
